name: fixed_width_underline_tab_indicator
description: "Custom TabBar indicator with a fixed-width underline for consistent emphasis."
version: 1.0.0
homepage: https://github.com/Matkurban/fixed_width_underline_tab_indicator
repository: https://github.com/Matkurban/fixed_width_underline_tab_indicator
topics: [widget, tabbar, indicator, flutter]

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
